image: node:17-alpine


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always




stages:
  - test
  - build
  - deploy


run_unit_tests:
  image: node:17-alpine
  tags:
    - shellrun
  stage: test
  before_script:
   - echo "Preparing test data" 
   - ./prepare-tests.sh
   
  script:
   - echo "Running unit tests"
  after_script:
    - echo " Cleaning up temporary files ..."


run_lint_tests:
  stage: test
  before_script:
   - echo "Preparing test data for $MICRO_SERVICE_NAME" and $PROPERTIES_FILE  
   - cat $PROPERTIES_FILE 
  script:
   - echo "Running lint tests"
   - npm version
  after_script:
    - echo " Cleaning up temporary files .."



build_image:
  only:
    - main
  stage: build
  script:
     - echo "Building image"
     - echo " Taggin the image"
     
push_image:
  stage: build
  needs:
    - build_image
  script:
    - echo " Logging to the registry"
    - echo "Pushing docker image to the registry"

deploy_image:
  only:
    - main
  stage: deploy
  script:
    - echo " Logging to the registry $DEPLOYMENT_ENVIROMENT"
    - echo "deployin docker image to the registry"






